---

version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile.app
      context: .
    environment:
      PORT: 5001
      JDBC_DATABASE_URL: jdbc:h2:mem:test
      JDBC_DATABASE_USERNAME: sa
      JDBC_DATABASE_PASSWORD: sa
      SPRING_PROFILES_ACTIVE: prod
      ROLLBAR_TOKEN: some_secret_token
    ports:
      - 5001:5001
