---
logging:
  level:
    root: WARN
    org:
      springframework:
        # web: DEBUG
        security: DEBUG

server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  instancio:
    bean:
      validation:
        enabled: true
  application:
    name: taskManager
  jpa:
    # generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

  # mvc:
  #   hiddenmethod:
  #     filter:
  #       enabled: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
